### ISSUE TITLE
sms package should probably be named termii

### ISSUE THREAD

**Issue by yeboahnanaosei** [gwuah/postmates#15]
The sms package is more or less a wrapper or client for the termii service. I think it will be great if it is called termii.
This way it will be easy to return more appropriate error messages that are specific to termii.

So the package path will look something like this: github.com/gwuah/postmates/sms/termii

Later, other sms wrappers can be grouped under the "sms" folder. So that, that folder will now become a module.
I already have such a module at https://github.com/yeboahnanaosei/sms :wink: 
It's a module that will hold several sms wrappers as and when I use them.

**Comment by oneEyedSunday** [comment]
Good stuff here
